services:
  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "90:8080"
    volumes:
      - ./keycloak-extensions:/opt/keycloak/providers
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Admin credentials
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      
      # Hostname configuration (v2)
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_HOSTNAME_STRICT: "false"
      
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://10.x.x.x:5432/dbname?ApplicationName=Keycloak&tcpKeepAlive=true&connectTimeout=10"
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      
      # Connection pool settings
      KC_DB_POOL_INITIAL_SIZE: "5"
      KC_DB_POOL_MIN_SIZE: "3"
      KC_DB_POOL_MAX_SIZE: "15"
      KC_TRANSACTION_XA_ENABLED: "false"
      
      # HTTP/Proxy configuration
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      
      # Cache configuration
      KC_CACHE: "local"
      
      # Health and metrics
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      
      # Logging
      KC_LOG_LEVEL: "info"
      KC_LOG_CONSOLE_OUTPUT: "default"
      
      # Timezone
      TZ: "Continent/Country"
      
    command: ["start"]
    
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
          
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
